shellEmulator: true

trustPolicy: no-downgrade

packages:
  - playground
  - docs
  - packages/*
  - examples/*

catalogs:
  cli:
    '@antfu/eslint-config': ^6.7.3
    bumpp: ^10.3.2
    eslint: ^9.39.2
    lint-staged: ^16.2.7
    simple-git-hooks: ^2.13.1
    tsx: ^4.21.0
    typescript: ^5.9.3
    unbuild: ^3.6.1
    vite: ^7.3.1
  inlined:
    '@antfu/utils': ^9.3.0
  prod:
    '@antfu/ni': ^28.1.0
    '@clack/prompts': ^0.11.0
    '@pnpm/workspace.find-packages': ^1000.0.54
    ansis: ^4.2.0
    cac: ^6.7.14
    fast-npm-meta: ^0.4.7
    find-up: ^8.0.0
    package-manager-detector: ^1.6.0
    pnpm-workspace-yaml: ^1.4.3
  testing:
    vitest: ^4.0.17
    vitest-package-exports: ^1.1.2
    yaml: ^2.8.2
  types:
    '@types/node': ^25.0.7
  utils:
    tinyexec: ^1.0.2

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
